### ISSUE TITLE
handler.js file 

### ISSUE THREAD

**Issue by tantsandras** [fac-15/MALM#11]
I know this is definitely a lack of time thing but the handler.js file is a bit untidy. 

![cleaning](https://media.giphy.com/media/A3tol87z1yJkk/giphy.gif)

**Comment by boi87** [comment]
We agree! Hopefully we'll get rid of the unused code and make it look tidy again.

**Comment by aterna01** [comment]
We still need commented code to apply it in Twitter API ))))
